### ISSUE TITLE
Font not generated

### ISSUE THREAD

**Issue by oanimadorcaipira** [Naereen/fontify#10]
Hello!

First, thank you for the amazing project! It's a nice and free alternative to other paid and closed ones. I get the app running but when I upload the PDF with the fonts I get the following error:

`convert: ../../magick/quantum.c:216: DestroyQuantumInfo: Assertiva “quantum_info != (QuantumInfo *) NULL” falhou.
127.0.0.1 - - [14/Jul/2019 16:12:29] "POST /upload-file HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/home/eta/Downloads/fontify/env/lib/python2.7/site-packages/werkzeug/serving.py", line 303, in run_wsgi
    execute(self.server.app)
  File "/home/eta/Downloads/fontify/env/lib/python2.7/site-packages/werkzeug/serving.py", line 294, in execute
    write(data)
  File "/home/eta/Downloads/fontify/env/lib/python2.7/site-packages/werkzeug/serving.py", line 257, in write
    self.send_header(key, value)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 412, in send_header
    self.wfile.write("%s: %s\r\n" % (keyword, value))
IOError: [Errno 32] Broken pipe`

Also, here is the PDF file I used: [out.pdf](https://github.com/Naereen/fontify/files/3390356/out.pdf)

Tell me if you need more information.

Thank you!

**Comment by Naereen** [comment]
Hi,
From what I see, the error comes from imagemagick's convert tool, see the first line of the error message you copied-pasted.
Try to update to the most recent version of imagemagick please?

**Comment by oanimadorcaipira** [comment]
I updated Imagemagick. I'm using version 6.9.7-4, but got the same error.
